// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abszmgesdgycymwmmjer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFic3ptZ2VzZGd5Y3ltd21tamVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3OTE3NTksImV4cCI6MjA2NDM2Nzc1OX0.xE84ppAcNLiqR7uITQAuq3VuCVobLZhCwhLip_zpC6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);